# Generated by Django 5.1.2 on 2024-10-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_populate_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('linux', 'Linux'), ('devops', 'DevOps'), ('docker', 'Docker'), ('code', 'Programming'), ('sql', 'SQL'), ('cms', 'CMS'), ('math', 'Mathematics'), ('history', 'History'), ('science', 'Science'), ('geography', 'Geography'), ('literature', 'Literature'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology')], max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
