# Generated by Django 5.0.6 on 2025-03-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('linux', 'Linux'), ('devops', 'DevOps'), ('docker', 'Docker'), ('code', 'Programming'), ('sql', 'SQL')], max_length=200),
        ),
    ]
